export const NamingRuleAdd = 'NamingRuleAdd'
export const NamingRuleDisable = 'NamingRuleDisable'
export const NamingRuleEnable = 'NamingRuleEnable'
export const NamingRuleRemove = 'NamingRuleRemove'
export const NameAdd = 'NameAdd'
export const NameRemove = 'NameRemove'
